

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."attribute_type" AS ENUM (
    'text',
    'image'
);


ALTER TYPE "public"."attribute_type" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."card" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "front_content" "text" NOT NULL,
    "notes" "text",
    "deck_id" bigint NOT NULL,
    "display_order" integer NOT NULL
);


ALTER TABLE "public"."card" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."card_attribute_value" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "value" "text" NOT NULL,
    "card_id" bigint NOT NULL,
    "deck_attribute_type_id" bigint NOT NULL
);


ALTER TABLE "public"."card_attribute_value" OWNER TO "postgres";


ALTER TABLE "public"."card_attribute_value" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."card_attribute_value_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."card" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."card_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."deck" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"()
);


ALTER TABLE "public"."deck" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."deck_attribute_type" (
    "id" bigint NOT NULL,
    "attribute_name" "text" NOT NULL,
    "display_order" integer NOT NULL,
    "deck_id" bigint NOT NULL,
    "attribute_type" "public"."attribute_type" DEFAULT 'text'::"public"."attribute_type" NOT NULL
);


ALTER TABLE "public"."deck_attribute_type" OWNER TO "postgres";


ALTER TABLE "public"."deck_attribute_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."deck_attribute_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."deck" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."deck_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."card_attribute_value"
    ADD CONSTRAINT "card_attribute_value_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."card"
    ADD CONSTRAINT "card_display_order_key" UNIQUE ("display_order");



ALTER TABLE ONLY "public"."card"
    ADD CONSTRAINT "card_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."deck_attribute_type"
    ADD CONSTRAINT "deck_attribute_type_attribute_name_key" UNIQUE ("attribute_name");



ALTER TABLE ONLY "public"."deck_attribute_type"
    ADD CONSTRAINT "deck_attribute_type_display_order_key" UNIQUE ("display_order");



ALTER TABLE ONLY "public"."deck_attribute_type"
    ADD CONSTRAINT "deck_attribute_type_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."deck"
    ADD CONSTRAINT "deck_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."deck"
    ADD CONSTRAINT "deck_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."card_attribute_value"
    ADD CONSTRAINT "card_attribute_value_card_id_fkey" FOREIGN KEY ("card_id") REFERENCES "public"."card"("id");



ALTER TABLE ONLY "public"."card_attribute_value"
    ADD CONSTRAINT "card_attribute_value_deck_attribute_type_id_fkey" FOREIGN KEY ("deck_attribute_type_id") REFERENCES "public"."deck_attribute_type"("id");



ALTER TABLE ONLY "public"."card"
    ADD CONSTRAINT "card_deck_id_fkey" FOREIGN KEY ("deck_id") REFERENCES "public"."deck"("id");



ALTER TABLE ONLY "public"."deck_attribute_type"
    ADD CONSTRAINT "deck_attribute_type_deck_id_fkey" FOREIGN KEY ("deck_id") REFERENCES "public"."deck"("id");



ALTER TABLE ONLY "public"."deck"
    ADD CONSTRAINT "deck_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



CREATE POLICY "Enable delete for users based on user_id" ON "public"."deck" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."deck" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for users based on user_id" ON "public"."card" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM "public"."deck" "deck"
  WHERE ("deck"."id" = "card"."deck_id"))));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."card_attribute_value" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM ("public"."deck_attribute_type"
     JOIN "public"."deck" ON (("deck_attribute_type"."deck_id" = "deck"."id")))
  WHERE ("deck_attribute_type"."id" = "card_attribute_value"."deck_attribute_type_id"))));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."deck_attribute_type" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM "public"."deck" "deck"
  WHERE ("deck"."id" = "deck_attribute_type"."deck_id"))));



CREATE POLICY "Enable update for users based on user_id" ON "public"."card" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM "public"."deck" "deck"
  WHERE ("deck"."id" = "card"."deck_id")))) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM "public"."deck" "deck"
  WHERE ("deck"."id" = "card"."deck_id"))));



CREATE POLICY "Enable update for users based on user_id" ON "public"."card_attribute_value" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM ("public"."deck_attribute_type"
     JOIN "public"."deck" ON (("deck_attribute_type"."deck_id" = "deck"."id")))
  WHERE ("deck_attribute_type"."id" = "card_attribute_value"."deck_attribute_type_id")))) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM ("public"."deck_attribute_type"
     JOIN "public"."deck" ON (("deck_attribute_type"."deck_id" = "deck"."id")))
  WHERE ("deck_attribute_type"."id" = "card_attribute_value"."deck_attribute_type_id"))));



CREATE POLICY "Enable users to view their own data only" ON "public"."card" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM "public"."deck" "deck"
  WHERE ("deck"."id" = "card"."deck_id"))));



CREATE POLICY "Enable users to view their own data only" ON "public"."card_attribute_value" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM ("public"."deck_attribute_type"
     JOIN "public"."deck" ON (("deck_attribute_type"."deck_id" = "deck"."id")))
  WHERE ("deck_attribute_type"."id" = "card_attribute_value"."deck_attribute_type_id"))));



CREATE POLICY "Enable users to view their own data only" ON "public"."deck" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable users to view their own data only" ON "public"."deck_attribute_type" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "deck"."user_id"
   FROM "public"."deck" "deck"
  WHERE ("deck"."id" = "deck_attribute_type"."deck_id"))));



ALTER TABLE "public"."card" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."card_attribute_value" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."deck" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."deck_attribute_type" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."card" TO "anon";
GRANT ALL ON TABLE "public"."card" TO "authenticated";
GRANT ALL ON TABLE "public"."card" TO "service_role";



GRANT ALL ON TABLE "public"."card_attribute_value" TO "anon";
GRANT ALL ON TABLE "public"."card_attribute_value" TO "authenticated";
GRANT ALL ON TABLE "public"."card_attribute_value" TO "service_role";



GRANT ALL ON SEQUENCE "public"."card_attribute_value_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."card_attribute_value_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."card_attribute_value_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."card_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."card_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."card_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."deck" TO "anon";
GRANT ALL ON TABLE "public"."deck" TO "authenticated";
GRANT ALL ON TABLE "public"."deck" TO "service_role";



GRANT ALL ON TABLE "public"."deck_attribute_type" TO "anon";
GRANT ALL ON TABLE "public"."deck_attribute_type" TO "authenticated";
GRANT ALL ON TABLE "public"."deck_attribute_type" TO "service_role";



GRANT ALL ON SEQUENCE "public"."deck_attribute_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."deck_attribute_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."deck_attribute_type_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."deck_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."deck_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."deck_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
